boards/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.auth import views as auth_views

from forums import views
from accounts import views as accounts_views

urlpatterns = [
    url(r'^boards/', include('forums.urls', namespace='forums')),
    # url(r'^reset/', include('accounts.urls', namespace='accounts')),
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.BoardListView.as_view(), name='home'),
    url(r'^signup/$', accounts_views.signup, name='signup'),
    url(r'^logout/$', auth_views.LogoutView.as_view(), name='logout'),
    url(r'^login/$', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    url(r'^reset/$', auth_views.PasswordResetView.as_view(
        template_name='accounts/password_reset.html',
        email_template_name='accounts/password_reset_email.html',
        subject_template_name='password_reset_subject.txt'
    ),
    name='password_reset'),
    url(r'^reset/done/$', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
        name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.PasswordResetConfirmView.as_view(template_name='accounts/password_reset_confirm.html'),
        name='password_reset_confirm'),
    url(r'^reset/complete/$', auth_views.PasswordResetCompleteView.as_view(
        template_name='accounts/password_reset_complete.html'),
        name='password_reset_complete'),
    url(r'^settings/password/$', auth_views.PasswordChangeView.as_view(
        template_name='accounts/password_change.html'), name='password_change'),
    url(r'^settings/password/done/$', auth_views.PasswordChangeDoneView.as_view(
        template_name='accounts/password_change_done.html'), name='password_change_done'),
    url(r'^settings/account/$', accounts_views.UserUpdateView.as_view(), name='my_account'),
]

forums/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/$', views.PostListView.as_view(), name='topic_posts'),
    url(r'(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/reply/$', views.reply_topic, name='reply_topic'),
    url(r'(?P<pk>\d+)/$', views.TopicListView.as_view(), name='board_topics' ),
    url(r'(?P<pk>\d+)/new/$', views.new_topic, name='new_topic'),
    url(r'(?P<pk>\d+)/topics/(?P<topic_pk>\d+)/posts(?P<post_pk>\d+)/edit/$',
        views.PostUpdateView.as_view(), name='edit_post'),
]

forums/models.py
import math
from django.db import models
from django.utils.text import Truncator
from django.contrib.auth.models import User
from django.utils.html import mark_safe
from markdown import markdown

# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=30, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

    def get_posts_count(self):
        return Post.objects.filter(topic__board=self).count()

    def get_last_post(self):
        return Post.objects.filter(topic__board=self).last()
        # return Post.objects.filter(topic__board=self).order_by('-created_at').first()


class Topic(models.Model):
    subject = models.CharField(max_length=255)
    last_updated = models.DateTimeField(auto_now_add=True)
    board = models.ForeignKey(Board, related_name='topics')
    starter = models.ForeignKey(User, related_name='topics')
    views = models.PositiveIntegerField(default=0)

    def __str__(self):
        return self.subject

    def get_page_count(self):
        count = self.posts.count()
        pages = count / 4
        return math.ceil(pages)

    def has_many_pages(self, count=None):
        if count is None:
            count = self.get_page_count()
        return count > 5

    def get_page_range(self):
        count = self.get_page_count()
        if self.has_many_pages(count):
            return range(1, 5)
        return range(1, count + 1)

    def get_last_five_posts(self):
        return self.posts.order_by('-created_at')[:5]


class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, related_name='posts')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(null=True)
    created_by = models.ForeignKey(User, related_name='posts')
    updated_by = models.ForeignKey(User, null=True, related_name='+')

    def __str__(self):
        truncated_message = Truncator(self.message)
        return truncated_message.chars(30)

    def get_message_as_markdown(self):
        return mark_safe(markdown(self.message, safe_mode='escape'))

forums/forms.py
from django import forms

from . import models

class NewTopicForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'rows': 5, 'placeholder': 'What is on your mind?'}),
                              max_length=4000,
                              help_text='The max length of the text is 4000.')

    class Meta:
        model = models.Topic
        fields = ['subject', 'message']

class PostForm(forms.ModelForm):
    class Meta:
        model = models.Post
        fields = ['message', ]

forums/views.py
from django.db.models import Count
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.views.generic import UpdateView, ListView
from django.utils import timezone
from django.utils.decorators import method_decorator
from django.urls import reverse

from . import models
from . import forms


class BoardListView(ListView):
    model = models.Board
    context_object_name = 'boards'
    template_name = 'forums/boards.html'




class TopicListView(ListView):
    model = models.Topic
    context_object_name = 'topics'
    template_name = 'forums/board_topics.html'
    paginate_by = 15

    def get_context_data(self, **kwargs):
        kwargs['board'] = self.board
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.board = get_object_or_404(models.Board, pk=self.kwargs.get('pk'))
        queryset = self.board.topics.order_by('-last_updated').annotate(replies=Count('posts') - 1)
        return queryset

@login_required
def new_topic(request, pk):
    board = get_object_or_404(models.Board, pk=pk)
    if request.method == 'POST':
        form = forms.NewTopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            topic.board = board
            topic.starter = request.user
            topic.save()
            post = models.Post.objects.create(
                message=form.cleaned_data.get('message'),
                topic=topic,
                created_by=request.user
            )
            return redirect('forums:topic_posts', pk=board.pk, topic_pk=topic.pk)
    else:
        form = forms.NewTopicForm()
    return render(request, 'forums/new_topic.html', {'form': form, 'board':board})

class PostListView(ListView):
    model = models.Post
    context_object_name = 'posts'
    template_name = 'forums/topic_posts.html'
    paginate_by = 4

    def get_context_data(self, **kwargs):

        session_key = 'viewed_topic_{}'.format(self.topic.pk)
        if not self.request.session.get(session_key, False):
            self.topic.views += 1
            self.topic.save()
            self.request.session[session_key] = True

        kwargs['topic'] = self.topic
        return super().get_context_data(**kwargs)

    def get_queryset(self):
        self.topic = get_object_or_404(models.Topic, board__pk=self.kwargs.get('pk'), pk=self.kwargs.get('topic_pk'))
        queryset = self.topic.posts.order_by('-created_at')
        return queryset


@login_required
def reply_topic(request, pk, topic_pk):
    topic = get_object_or_404(models.Topic, board__pk=pk, pk=topic_pk)
    if request.method == 'POST':
        form = forms.PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.created_by = request.user
            post.save()

            topic.last_updated = timezone.now()
            topic.save()

            topic_url = reverse('forums:topic_posts', kwargs={'pk': pk, 'topic_pk': topic_pk})
            topic_post_url = '{url}?page={page}#{id}'.format(
                url=topic_url,
                id=post.pk,
                page=topic.get_page_count()
            )

            return redirect(topic_post_url)
    else:
        form = forms.PostForm()
    return render(request, 'forums/reply_topic.html', {'topic': topic, 'form': form})


@method_decorator(login_required, name='dispatch')
class PostUpdateView(UpdateView):
    model = models.Post
    fields = ('message', )
    template_name = 'forums/edit_post.html'
    pk_url_kwarg = 'post_pk'
    context_object_name = 'post'

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(created_by=self.request.user)

    def form_valid(self, form):
        post = form.save(commit=False)
        post.updated_by = self.request.user
        post.updated_at = timezone.now()
        post.save()
        return redirect('forums:topic_posts', pk=post.topic.board.pk, topic_pk=post.topic.pk)

forums/templates/forums/board_topics.html
{% extends 'base.html' %}

{% load humanize %}

{% block title %}{{ board.name }} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item active">{{ board.name }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'forums:new_topic' pk=board.pk %}" class="btn btn-outline-primary">New Topic</a>
    </div>

    <table class="table table-striped mb-4">
        <thead class="thead-dark">
            <tr>
                <th>Topic</th>
                <th>Starter</th>
                <th>Replies</th>
                <th>Views</th>
                <th>Last Updated</th>
            </tr>
        </thead>
        <tbody>
            {% for topic in topics %}
                {% url 'forums:topic_posts' pk=board.pk topic_pk=topic.pk as topic_url %}
                <tr>
                    <td>
                        <p class="mb-0">
                            <a href="{{ topic_url }}">{{ topic.subject }}</a>
                        </p>
                        <small class="text-muted">
                            Pages:
                            {% for i in topic.get_page_range %}
                                <a href="{{ topic_url }}?page={{ i }}">{{ i }}</a>
                            {% endfor %}
                            {% if topic.has_many_pages %}
                                ... <a href="{{ topic_url }}?page={{ topic.get_page_count }}">Last Page</a>
                            {% endif %}
                        </small>
                    </td>
                    <td>{{ topic.starter.username }}</td>
                    <td>{{ topic.replies }}</td>
                    <td>{{ topic.views }}</td>
                    <td>{{ topic.last_updated|naturaltime }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

    {% include 'includes/pagination.html' %}

{% endblock %}

forums/templates/forums/boards.html
{% extends 'base.html' %}

{% block title %}Boards | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item active">Boards</li>
{% endblock %}

{% block content %}

    <table class="table">
        <thead class="thead-dark">
            <tr>
                <th>Board</th>
                <th>Posts</th>
                <th>Topics</th>
                <th>Last Post</th>
            </tr>
        </thead>
        <tbody>
            {% for board in boards %}
                <tr>
                    <td>
                        <a href="{% url 'forums:board_topics' pk=board.pk %}">{{ board.name }}</a>
                        <small class="text-muted d-block">{{ board.description }}</small>
                    </td>
                    <td class="align-middle">{{ board.get_posts_count }}</td>
                    <td class="align-middle">{{ board.topics.count }}</td>
                    <td class="align-middle">
                        {% if board.get_posts_count %}
                            {% with post=board.get_last_post %}
                                <a href="{% url 'forums:topic_posts' pk=board.pk topic_pk=post.topic.pk %}">
                                    By {{ post.created_by.username }} at {{ post.created_at }}
                                </a>
                            {% endwith %}
                        {% else %}
                            <small class="text-muted">There is nothing here yet.</small>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

forums/templates/forums/edit_post.html
{% extends 'base.html' %}

{% block title %}Edit post | {{ block.super }}{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script>
        var simplemde = new SimpleMDE();
    </script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:board_topics' pk=post.topic.board.pk %}">{{ post.topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:topic_posts' pk=post.topic.board.pk topic_pk=post.topic.pk %}">{{ post.topic.subject }}</a></li>
    <li class="breadcrumb-item active">Edit post</li>
{% endblock %}

{% block content %}
    <form method="POST" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-outline-success">Save changes</button>
        <a href="{% url 'forums:topic_posts' pk=post.topic.board.pk topic_pk=post.topic.pk %}" class="btn btn-outline-danger">Cancel</a>
    </form>
{% endblock %}

forums/templates/forums/new_topic.html
{% extends 'base.html' %}

{% load widget_tweaks %}

{% block title %}New Topic | {{ board.name }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:board_topics' pk=board.pk %}">{{ board.name }}</a></li>
    <li class="breadcrumb-item active">New Topic</li>
{% endblock %}

{% block content %}
    <form method="POST" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-outline-success">Post</button>
    </form>
{% endblock %}

forums/templates/forums/reply_topic.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Reply {{ topic.subject }} | {{ block.super }}{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.css">
{% endblock %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/simplemde/latest/simplemde.min.js"></script>
    <script>
        var simplemde = new SimpleMDE();
    </script>
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:board_topics' pk=topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:topic_posts' pk=topic.board.pk topic_pk=topic.pk %}">{{ topic.subject }}</a></li>
    <li class="breadcrumb-item active">Reply</li>
{% endblock %}

{% block content %}
    <form method="POST" class="mb-4" novalidate>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-outline-success">Post a reply</button>
    </form>

    {% for post in topic.get_last_five_posts %}
        <div class="card mb-2">
            <div class="card-body p-3">
                <div class="row mb-3">
                    <div class="col-6">
                        <strong class="text-muted">{{ post.created_by.username }}</strong>
                    </div>
                    <div class="col-6 text-right">
                        <small class="text-muted">{{ post.created_at }}</small>
                    </div>
                </div>
                {{ post.get_message_as_markdown }}
            </div>
        </div>
    {% endfor %}

{% endblock %}

forums/templates/forums/topic_posts.html
{% extends 'base.html' %}

{% load static %}
{% load gravatar %}

{% block title %}{{ topic.subject }} | {{ block.super }}{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Boards</a></li>
    <li class="breadcrumb-item"><a href="{% url 'forums:board_topics' pk=topic.board.pk %}">{{ topic.board.name }}</a></li>
    <li class="breadcrumb-item active">{{ topic.subject }}</li>
{% endblock %}

{% block content %}
    <div class="mb-4">
        <a href="{% url 'forums:reply_topic' pk=topic.board.pk topic_pk=topic.pk %}" class="btn btn-outline-primary">Reply</a>
    </div>

    {% for post in posts %}
        <div id="{{ post.pk }}" class="card {% if forloop.last %}mb-4{% else %}mb-2{% endif %} {% if forloop.first %}border-dark{% endif %}">
            {% if forloop.first %}
                <div class="card-header text-dark py-2 px-3" style="background-color: #fff1b0">{{ topic.subject }}</div>
            {% endif %}
            <div class="card-body p-3">
                <div class="row">
                    <div class="col-2">
                        <img src="{{ post.created_by|gravatar }}" alt="{% static 'img/avatar.svg' %}" class="w-100">
                        <small>Posts: {{ post.created_by.posts.count }}</small>
                    </div>
                    <div class="col-10">
                        <div class="row mb-3">
                            <div class="col-6">
                                <strong class="text-muted">{{ post.created_by.username }}</strong>
                            </div>
                            <div class="col-6 text-right">
                                <small class="text-muted">{{ post.created_at }}</small>
                            </div>
                        </div>
                        {{ post.get_message_as_markdown }}
                        {% if post.created_by == user %}
                            <div class="mt-3">
                                <a href="{% url 'forums:edit_post' pk=post.topic.board.pk topic_pk=post.topic.pk post_pk=post.pk %}"
                                   class="btn btn-outline-info">
                                    Edit
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    {% endfor %}

    {% include 'includes/pagination.html' %}

{% endblock %}